### ISSUE TITLE
Parse variables in PKGBUILD when upgrading from AUR

### ISSUE THREAD

**Issue by ghost** [ushis/local-repo#28]
If a PKGBUILD has "depends=( ${_pkgbase} )" or in 'makedepends', local-repo should translate this variable to the correct value, instead of looking for package '${_pkgbase}' which is the current behavior when trying to upgrade from AUR.

The presence of this variable in 'depends'  is very common in "lib32" packages in AUR and [multilib] repo.

**Comment by ushis** [comment]
ok, its on the list for 1.5

are you interested in implementing it?

**Comment by ushis** [comment]
@ghost ok its in devel. can you please test it?
