### ISSUE TITLE
LocalRepo.aur_upgrade() has bad version comparison

### ISSUE THREAD

**Issue by ushis** [ushis/local-repo#36]
The lexical comparison of the version strings in `LocalRepo.aur_upgrade()` is crap. The result is that something like `'100' > '59'` is `False`.

**Comment by feuri** [comment]
In line 203 we compare strings, not integers and a string beginning with a `'5'` is bigger than one beginning with a `'1'`. We should convert the strings to integers using the `int()` function.

**Comment by feuri** [comment]
Arg, forget about it, there can be version like `'latest-1'`, which are obviously NOT integers.

**Comment by ushis** [comment]
There is a python module called `distutils.version`. This should do the job, but the docu lacks: http://docs.python.org/distutils/apiref.html#module-distutils.version
