### ISSUE TITLE
Logging!

### ISSUE THREAD

**Issue by ushis** [ushis/local-repo#41]
What about logging? It should be optional. The log file should be specified in the config - if not, no logging...

**Comment by feuri** [comment]
What about something like this?

```
$logdir # the path where the logs are stored
├── buildlog # logs for building packages ('makepkg -L', needs 'tee')
│   ├── pkg1 # logs for pkg1
│   │   └── pkg1-3.2-1-x86_64.log # logfile for pkg1
│   ├── pkg2 # logs for pkg2
│   │   ├── pkg2-1.3-1-x86_64.log # logfile for pkg2
│   │   └── pkg2-1.4-1-x86_64.log # logfile for pkg2
│   ├── pkg3 # logs for pkgN
│   │   └── pkg3-1.0-1-x86_64.log # logfile for pkg3
│   └── pkgN # logs for pkgN
└── local-repo.log # logfile for local-repo itself
```

**Comment by ushis** [comment]
@feuri looks good to me. 'tee' is in 'coreutils' so this should be no problem.

Some suggestions:
- local-repo log goes to /path/to/repo/.log (like .cache) by default, but can be overwritten in the config
- buildlog must explicitly be enabled by setting `buildlog = path` in the config

**Comment by feuri** [comment]
Sounds great!

**Comment by ushis** [comment]
> local-repo log goes to /path/to/repo/.log (like .cache) by default, but can be overwritten in the config

Finished this - its in the 'devel' branch

**Comment by ushis** [comment]
Ok its done. @feuri Can you test it please? Its in the buildlog branch. Dont forget to specify the _buildlog_ path in your config.

**Comment by ushis** [comment]
what about storing the latest _PKGBUILD_ in _buildlog/pkgname/_ too?

**Comment by feuri** [comment]
```
[2012-03-22 19:47] Forging a new package: https://aur.archlinux.org/packages/py/python3-stagger-svn/python3-stagger-svn.tar.gz
[2012-03-22 19:48] [Error] An error occurred while running: /usr/bin/makepkg -d -L # -> buildlog completely missing
[2012-03-22 19:51] Starting an AUR upgrade
[2012-03-22 19:52] Removed packages: wow-2-themes, wow-themes
[2012-03-22 19:52] Forging a new package: https://aur.archlinux.org/packages/wo/wow-themes/wow-themes.tar.gz
[2012-03-22 19:53] Added Package: wow-themes latest-1 # buildlog stored, but only 1kb
[2012-03-22 19:53] Forging a new package: https://aur.archlinux.org/packages/wo/wow-2-themes/wow-2-themes.tar.gz
[2012-03-22 19:53] Added Package: wow-2-themes latest-1 # buildlog stored, but only 1kb
```

Strange...

Storing the last 'PKGBUILD' too is a great idea.

**Comment by feuri** [comment]
The almost empty buildlogs seem to be tee's fault.

**Comment by ushis** [comment]
@feuri empty logs are tees fault thats right. missing logs are my fault...

**Comment by ushis** [comment]
ok - fixed missing logs - @feuri can you test it please

**Comment by feuri** [comment]
Works now. Every buidlog is stored and complete.

**Comment by ushis** [comment]
@feuri Thanks for testing. Is it enough to store the PKGBUILD file or should we store every file we find in the tarball (e.g. *.install, other source files)?

**Comment by feuri** [comment]
The PKGBUILD itself is useless without the other files found in the tarball, so we should store everything. (Or we let the user decide, what he wants to be stored)

**Comment by ushis** [comment]
hmm, so we need one more dir: _buildlog/pkgname/pkgbuild/_. hahaha - the buildlog dir will become a huge scrapyard. will think about that

**Comment by feuri** [comment]
Move the PKGBUILDs to 'pkgbuild/pkgname' or use 'pkname/buildlog' and 'pkgname/pkgbuild'.

**Comment by ushis** [comment]
BAAAM. What about this:
1. People can specify a _pkgbuild_ path in the config
2. We add the `--rebuild pkgname pkgname` switch
3. If _pkgbuild_ is specified in the config people can rebuild their packages

**Comment by feuri** [comment]
Nothing to complain

**Comment by ushis** [comment]
@feuri Lets test `--rebuild pkgname`, which is just a shortcut for `-fa /path/to/my/pkgbuilds/pkgname`

**Comment by feuri** [comment]
Just getting ''Could not load PKGBUILD into workspace: ' :S

**Comment by ushis** [comment]
@feuri can you please pull and try it again and post the ouput? Aaaa, dont need this anymore - im stupid!

**Comment by feuri** [comment]
'Could not load PKGBUILD into workspace: /home/jonas/code/python/local-repo/testrepo/pkgbuild/archey -> /tmp/local-repo-nna0j1/tmpsg400a'
The first dir is correct.

**Comment by ushis** [comment]
@feuri think i did it

**Comment by feuri** [comment]
Yep, works now.

**Comment by ushis** [comment]
Great - will close this issue. Lets run some tests and send 1.6 into the wild!
