### ISSUE TITLE
Poor elephant forgotten :/

### ISSUE THREAD

**Issue by rffontenelle** [ushis/local-repo#43]
Prior today (march 24 2012), " --elephant" didn't need any parameter, as it stated in the help output. Right now, it will not work. Can you please fix this funny feature?

$ LC_ALL=C local-repo --help | grep elephant
  -e, --elephant        the elephant never forgets

$ LC_ALL=C local-repo --elephant
usage: local-repo path [options]
local-repo: error: too few arguments

**Comment by ushis** [comment]
@josephgbr try `$ local-repo /tmp -e` the first argument needs to be specified, even its a random **existing** directory.

The help says `usage: local-repo path [options]`

**Comment by rffontenelle** [comment]
Oh I see it now. But should it be necessary in this case?

**Comment by ushis** [comment]
@josephgbr Its the only option where this makes no sense. And i dont want to break consistency and write some extra code for a _just for fun feature_. Hope that is ok for you...

**Comment by rffontenelle** [comment]
no problem at all, it works anyways.

**Comment by ushis** [comment]
Ok, cool - so i'll close this issue
