### ISSUE TITLE
Can't remove bogus package from repo

### ISSUE THREAD

**Issue by rffontenelle** [ushis/local-repo#48]
An already added package doesn't have URL, which is interpreted as a "invalid db entry" by local-repo. Due to this fact, I can not do some (all?) operations with this repo. e.g. can't remove this package.

$ LC_ALL=C local-repo rafaelrepo -f -r gtksourceview2-pkgbuild

> Loading repo: /var/lib/local-repo
> Invalid db entry: gtksourceview2-pkgbuild-0.1.0-3/desc: Missing fields: url

p.s.: I used an ugly workaround to solved this issue (manually removed pacakge and rebuilt the repo rb).

**Comment by ushis** [comment]
@josephgbr thx for the report. i'll look into this. Can you please post the PKGBUILD somewhere for testing purposes?

**Comment by ushis** [comment]
@josephgbr how was it even possible to add this package with local-repo?

**Comment by rffontenelle** [comment]
@ushis I don't have this PKGBUILD anymore, but it was added with initial versions of local-repo. Indeed seems that right now it is avoiding this kind of issue. I just don't know how I can test it again, as local-repo won't allow me to add the bogus package to the repo db :o)

**Comment by ushis** [comment]
@josephgbr you can reproduce this by modifying the database by hand or running

```
$ repo-add mydb.db.tar.gz bad-package.pkg.tar.xz
```

i think i will add some repair functionality to the `--check` switch

**Comment by rffontenelle** [comment]
Ok, added a bogus package, but failed to remove with '-f' and '--force' and without them.

$ LC_ALL=C local-repo rafaelrepo -f -r gtksourceview3-pkbuild

> Loading repo: /var/lib/local-repo
> Invalid db entry: gtksourceview3-pkgbuild-0.1.0-2/desc: Missing fields: url

$ yaourt -Q local-repo-git
local-repo/local-repo-git 20120421-1

**Comment by ushis** [comment]
@josephgbr yes, that's because i haven't done anything yet... hehe. my changes should have solved issue #49 not this one.

**Comment by rffontenelle** [comment]
@ushis oh, I saw today's commit and I think it was done. My mistake. :)

**Comment by ushis** [comment]
Ok, i made the DatabaseParser more tolerant for missing fields, so the problem only occurs, if your database is definitely screwed.
