### ISSUE TITLE
Forward --force to makepkg [-f]

### ISSUE THREAD

**Issue by rffontenelle** [ushis/local-repo#49]
Trying --aur-upgrade, but it seems the package is already built. It suggests to use --force/-f to overwrite, but it doesn't work.

$ LC_ALL=C local-repo rafaelrepo --force -U

> Loading repo: /var/lib/local-repo
> 258 packages found
> Retrieving package info from the AUR
> 84 packages found
> Checking for updates
> lib32-icu (4.8.1.1-1 -> 4.8.1.1-2)
> Upgrade? [y|N] y
> Forging a new package: https://aur.archlinux.org/packages/li/lib32-icu/lib32-icu.tar.gz
> [=========================] 100%
> ==> ERROR: A package has already been built. (use -f to overwrite)
> An error occurred while running: /usr/bin/makepkg -d -L -m --nosign

**Comment by rffontenelle** [comment]
FYI, I set PKGDEST, SRCDEST and SRCDEST  in /etc/makepkg.conf, which might be the reason why local-repo notice a existent package.

**Comment by ushis** [comment]
@josephgbr You don't need --force together with --aur-upgrade. It only makes sense with --add and --aur-add.

But this error is strange. local-repo builds the packages in its own temporary dir, which is cleaned up before building a package.. I'll have a look. Please try it again. Do you have some fancy setup in you makepkg.conf?

**Comment by ushis** [comment]
@josephgbr This error comes from makepkg not from local-repo. I could add the -f option to the makepkg call to prevent this error.

**Comment by rffontenelle** [comment]
@ushis it could ask "A package has already been built. Do you want to overwrite? [y/N]". In case yes, then add '-f' to makepkg options.

**Comment by ushis** [comment]
Does makepkg has a specific error code for this case? I would need this to determine that it is this particular error. On the other hand PKGDEST in makepkg.conf makes no real sense, when using local-repo.

**Comment by rffontenelle** [comment]
@ushis Related to the error from makepkg, can't you add the '-f' option to makepkg when user run "local-repo repo --force" ?

**Comment by ushis** [comment]
Another possibility is to add a config entry, to force local-repo to append the -f switch to the makepkg call.

**Comment by rffontenelle** [comment]
@ushis answering your last comment above, If no "-f" is informed to makepkg, then I see the aformentioned error message. If "--force" is mentioned, it simply ignores the existent package, and build another - simply it goes on.

**Comment by ushis** [comment]
Sounds good. Will do it this way.

**Comment by ushis** [comment]
@josephgbr i just added the -f switch to the makepkg call c8cfb0eb5558955f0c5d2d374695554f9c9dd580 but will change that, when i have more time. please test the devel branch.

**Comment by rffontenelle** [comment]
@ushis Ok, I can confirm it is working. I was able to overwrite a existent package without problems. Thanks.
