### ISSUE TITLE
repo db's filename is the same name as folder in path

### ISSUE THREAD

**Issue by rffontenelle** [ushis/local-repo#50]
Instead of providing to repodb file the same name as repo, the repodb filename is created with the same name as the folder's. For example, reponame=myrepo and path=/var/cache/anothername : if the database is rebuilt, the repodb filename will be "anothername.db.tar.gz", inside /var/cache/anothername.

This is partically weird if I add my local repository to '/etc/pacman.conf'. I would expect to have [myrepo] name, but pacman would find only [anothername] as repo name.

The repodb filename shouldn't follow the name of the repo's name?

**Comment by ushis** [comment]
@josephgbr think this is done with d08029b762061e15ba1395e6270f3941a6435e01. please test it.

**Comment by rffontenelle** [comment]
@ushis yep, problem solved, Thanks!
