### ISSUE TITLE
Failed to load $CARCH from /etc/makepkg.conf

### ISSUE THREAD

**Issue by rffontenelle** [ushis/local-repo#51]
Trying to build [gngeo from AUR](http://aur.archlinux.org/packages.php?ID=1529) but it seems local-repo didn't load $CARCH variable. This variable is set in /etc/makepkg.conf (in my case, should return 'x86_64') and gngeo's PKGBUILD is loading it outside and inside build() function. This PKGBUILD normally would work fine.

See output :

$ LC_ALL=C lr -a http://aur.archlinux.org/packages/gn/gngeo/gngeo.tar.gz

> Loading repo: /var/cache/rafaelrepo
> Forging a new package: http://aur.archlinux.org/packages/gn/gngeo/gngeo.tar.gz
> [=========================] 100%
> /tmp/local-repo-1rckl4/gngeo/PKGBUILD: line 12: [: ==: unary operator expected
> /tmp/local-repo-1rckl4/gngeo/PKGBUILD: line 15: [: ==: unary operator expected
> ==> Making package: gngeo 0.8-4 (Sat Apr 21 23:20:56 BRT 2012)
> ==> WARNING: Skipping dependency checks.
> ==> Retrieving Sources...
>   -> Found gngeo-0.8.tar.gz
>   -> Found 4dec1ccfb85d.patch
> ==> Validating source files with md5sums...
>     gngeo-0.8.tar.gz ... Passed
>     4dec1ccfb85d.patch ... Passed
> ==> Extracting Sources...
>   -> Extracting gngeo-0.8.tar.gz with bsdtar
> ==> Starting build()...
> patching file src/star_interf.c
> patching file src/raze_interf.c
> checking build system type... x86_64-unknown-linux-gnu
> checking host system type... x86_64-unknown-linux-gnu
> checking target system type... x86_64-unknown-linux-gnu
> checking for a BSD-compatible install... /usr/bin/install -c
> checking whether build environment is sane... yes
> checking for a thread-safe mkdir -p... /bin/mkdir -p
> checking for gawk... gawk
> checking whether make sets $(MAKE)... yes
> checking for gcc... gcc -m32
> checking whether the C compiler works... yes
> checking for C compiler default output file name... a.out
> checking for suffix of executables... 
> checking whether we are cross compiling... no
> checking for suffix of object files... o
> checking whether we are using the GNU C compiler... yes
> checking whether gcc -m32 accepts -g... yes
> checking for gcc -m32 option to accept ISO C89... none needed
> checking for style of include used by make... GNU
> checking dependency style of gcc -m32... gcc3
> checking for ranlib... ranlib
> checking dependency style of gcc -m32... gcc3
> checking for sdl-config... /usr/bin/sdl-config-32
> checking for SDL - version >= 1.2.0... ./configure: line 4251: /usr/bin/sdl-config-32: No such file or directory
> ./configure: line 4252: /usr/bin/sdl-config-32: No such file or directory
> ./configure: line 4255: /usr/bin/sdl-config-32: No such file or directory
> ./configure: line 4257: /usr/bin/sdl-config-32: No such file or directory
> ./configure: line 4259: /usr/bin/sdl-config-32: No such file or directory
> no
> **\* Could not run SDL test program, checking why...
> **\* The test program failed to compile or link. See the file config.log for the
> **\* exact error that occured. This usually means SDL was incorrectly installed
> **\* or that you have moved SDL since it was installed. In the latter case, you
> **\* may want to edit the sdl-config script: /usr/bin/sdl-config-32
> configure: error: **\* SDL version 1.2.0 not found!
> ==> ERROR: A failure occurred in build().
>     Aborting...
> An error occurred while running: /usr/bin/makepkg -d -f -L -m --nosign

**Comment by ushis** [comment]
@josephgbr does makepkg alone work fine?

**Comment by rffontenelle** [comment]
Yep, see log below:

$ LC_ALL=C makepkg -fs
==> Making package: gngeo 0.8-4 (Sat Apr 21 23:47:37 BRT 2012)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving Sources...
  -> Found gngeo-0.8.tar.gz
  -> Found 4dec1ccfb85d.patch
==> Validating source files with md5sums...
    gngeo-0.8.tar.gz ... Passed
    4dec1ccfb85d.patch ... Passed
==> Extracting Sources...
  -> Extracting gngeo-0.8.tar.gz with bsdtar
==> Starting build()...
patching file src/star_interf.c
patching file src/raze_interf.c
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking target system type... x86_64-unknown-linux-gnu
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking for gcc... gcc -m32
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc -m32 accepts -g... yes
checking for gcc -m32 option to accept ISO C89... none needed
checking for style of include used by make... GNU
checking dependency style of gcc -m32... gcc3
checking for ranlib... ranlib
checking dependency style of gcc -m32... gcc3
checking for sdl-config... /usr/bin/sdl-config-32
checking for SDL - version >= 1.2.0... yes
(... etc... )

**Comment by ushis** [comment]
@josephgbr Ok, fix is the devel branch. Please test.

**Comment by rffontenelle** [comment]
@ushis yep, issue solved. Thanks
