### ISSUE TITLE
Add exception to '--aur-upgrade' option

### ISSUE THREAD

**Issue by rffontenelle** [ushis/local-repo#53]
Sometimes, the package's PKGBUILD in AUR is messed up and it won't build until the maintainer get it fixed. It would be nice to have implemented an exception option to this command. Something like '--ignore <pkg>' (quoting an option of  "pacman -S").

**Comment by ushis** [comment]
Please use 'no-aur-upgrade' in your config. See: http://ushi.wurstcase.net/local-repo/#conf-no-aur-upgrade

**Comment by rffontenelle** [comment]
@ushis oh i see it now. Thanks.

**Comment by ushis** [comment]
your welcome. if your list becomes too long, you can continue on a new **indented** line.
