### ISSUE TITLE
Won't install/update package with plus sign in pkgname

### ISSUE THREAD

**Issue by rffontenelle** [ushis/local-repo#55]
This package is in AUR, but it seems that the '++' is messing things up.

$ LC_ALL=C lr -A lib32-libsigc++

> Loading repo: /var/cache/rafaelrepo
> Retrieving package info from the AUR
> AUR responded with error: No results found

**Comment by rffontenelle** [comment]
On the other side, I can easily add it locally with '-a <*.pkg.tar.xz>'.

**Comment by ushis** [comment]
@josephgbr should work now.

**Comment by rffontenelle** [comment]
Indeed works. Thanks!
