### ISSUE TITLE
failed to automatically remove [pkgname>=pkgver], installed as dependency

### ISSUE THREAD

**Issue by rffontenelle** [ushis/local-repo#57]
When building a lib32-nss [1] , had to install lib32-nspr [2] as dependency. However 'lib32-nspr>=4.9' how it is represented in the source array. So, after compilation is done, local-repo asks if it should remove the dependency, but fail to get the correct package name.

Procedure to reproduce:
- compile lib32-nspr and add to repo db
- update pacman's db
- start compilation of lib32-nss with local-repo
- install needed package, lib32-nspr
- after compilation, it asks if it should remove 'lib32-nspr>=4.9'
- After 'y', it fails.

Output:

==> Finished making: lib32-nss 3.13.3-1 (Sat May 26 02:08:36 BRT 2012)
Installed following packages as dependencies:
[lib32-nspr>=4.9]
Uninstall? [y|N] y
error: target not found: lib32-nspr>=4.9
An error occurred while running: /usr/bin/sudo /usr/bin/pacman -R lib32-nspr>=4.9

**Comment by ushis** [comment]
A crap, ok. I will look into this.

**Comment by ushis** [comment]
@josephgbr Can you please checkout the devel branch. It should be fixed with 1282403413140434053f13da22838b2f418bbf7a

**Comment by rffontenelle** [comment]
Works just fine now. Thanks!
